# Generated by Django 4.0.2 on 2022-02-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_category_category_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size_unit',
            options={'verbose_name': 'Size Type', 'verbose_name_plural': 'Size Types'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status_type',
            old_name='type_name',
            new_name='name',
        ),
    ]
