# Generated by Django 4.0.2 on 2022-02-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_image_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size_unit',
            old_name='type_name',
            new_name='unit_name',
        ),
    ]
