# Generated by Django 4.0.2 on 2022-02-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_rename_type_name_size_unit_unit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size_unit',
            options={'verbose_name': 'Size Unit', 'verbose_name_plural': 'Size Units'},
        ),
    ]
