# Generated by Django 4.0.2 on 2022-02-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0002_remove_image_product_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='banners')),
                ('set_show', models.BooleanField(default=False)),
            ],
        ),
    ]
