# Generated by Django 4.0.2 on 2022-02-21 08:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='w_blog',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
