# Generated by Django 4.0.2 on 2022-02-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_w_blog_alter_blog_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='w_blog',
        ),
    ]
