# Generated by Django 4.0.2 on 2022-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='otp',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
