# Generated by Django 4.0.2 on 2022-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_data_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
